/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      keyframes: {
        bob: {
          "0%, 100%": { transform: "translateY(0px) rotate(-3deg)" },
          "50%": { transform: "translateY(-8px) rotate(3deg)" },
        },
        bobSlow: {
          "0%, 100%": { transform: "translateY(0px) rotate(2deg)" },
          "50%": { transform: "translateY(-6px) rotate(-2deg)" },
        },
        slideUp: {
          "0%": { transform: "translateY(40px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        coinPop: {
          "0%": { transform: "scale(0) translateY(0)", opacity: "1" },
          "70%": { transform: "scale(1.4) translateY(-30px)", opacity: "1" },
          "100%": { transform: "scale(1) translateY(-50px)", opacity: "0" },
        },
        giftShake: {
          "0%":   { transform: "rotate(0deg) scale(1)" },
          "5%":   { transform: "rotate(-6deg) scale(1.05)" },
          "10%":  { transform: "rotate(6deg) scale(1.05)" },
          "15%":  { transform: "rotate(-6deg) scale(1.05)" },
          "20%":  { transform: "rotate(6deg) scale(1.05)" },
          "25%":  { transform: "rotate(0deg) scale(1)" },
          "35%":  { transform: "rotate(0deg) scale(1)" },
          "40%":  { transform: "rotate(-10deg) scale(1.08)" },
          "45%":  { transform: "rotate(10deg) scale(1.08)" },
          "50%":  { transform: "rotate(-10deg) scale(1.08)" },
          "55%":  { transform: "rotate(10deg) scale(1.08)" },
          "60%":  { transform: "rotate(-10deg) scale(1.08)" },
          "65%":  { transform: "rotate(0deg) scale(1)" },
          "75%":  { transform: "rotate(0deg) scale(1)" },
          "80%":  { transform: "rotate(-14deg) scale(1.12)" },
          "85%":  { transform: "rotate(14deg) scale(1.12)" },
          "90%":  { transform: "rotate(-14deg) scale(1.12)" },
          "95%":  { transform: "rotate(14deg) scale(1.12)" },
          "100%": { transform: "rotate(0deg) scale(1)" },
        },
        duckReveal: {
          "0%":   { transform: "translateY(40px) scale(0.4)", opacity: "0" },
          "50%":  { transform: "translateY(-12px) scale(1.15)", opacity: "1" },
          "75%":  { transform: "translateY(4px) scale(0.97)", opacity: "1" },
          "100%": { transform: "translateY(0px) scale(1)", opacity: "1" },
        },
        revealBox: {
          "0%": { transform: "scale(0.5) rotate(-10deg)", opacity: "0" },
          "60%": { transform: "scale(1.1) rotate(3deg)", opacity: "1" },
          "100%": { transform: "scale(1) rotate(0deg)", opacity: "1" },
        },
        swim1: {
          "0%":   { transform: "translateX(0px) translateY(0px) rotate(-3deg)" },
          "20%":  { transform: "translateX(18px) translateY(-7px) rotate(2deg)" },
          "40%":  { transform: "translateX(30px) translateY(-2px) rotate(-2deg)" },
          "60%":  { transform: "translateX(14px) translateY(-9px) rotate(3deg)" },
          "80%":  { transform: "translateX(-10px) translateY(-4px) rotate(-3deg)" },
          "100%": { transform: "translateX(0px) translateY(0px) rotate(-3deg)" },
        },
        swim2: {
          "0%":   { transform: "translateX(0px) translateY(0px) rotate(2deg)" },
          "25%":  { transform: "translateX(-20px) translateY(-8px) rotate(-3deg)" },
          "50%":  { transform: "translateX(-32px) translateY(-3px) rotate(2deg)" },
          "75%":  { transform: "translateX(-16px) translateY(-10px) rotate(-2deg)" },
          "100%": { transform: "translateX(0px) translateY(0px) rotate(2deg)" },
        },
        swim3: {
          "0%":   { transform: "translateX(0px) translateY(0px) rotate(-1deg)" },
          "30%":  { transform: "translateX(24px) translateY(-6px) rotate(3deg)" },
          "55%":  { transform: "translateX(10px) translateY(-11px) rotate(-2deg)" },
          "80%":  { transform: "translateX(-18px) translateY(-5px) rotate(2deg)" },
          "100%": { transform: "translateX(0px) translateY(0px) rotate(-1deg)" },
        },
        swim4: {
          "0%":   { transform: "translateX(0px) translateY(0px) rotate(3deg)" },
          "20%":  { transform: "translateX(-14px) translateY(-9px) rotate(-2deg)" },
          "50%":  { transform: "translateX(20px) translateY(-4px) rotate(3deg)" },
          "70%":  { transform: "translateX(28px) translateY(-8px) rotate(-3deg)" },
          "100%": { transform: "translateX(0px) translateY(0px) rotate(3deg)" },
        },
        swim5: {
          "0%":   { transform: "translateX(0px) translateY(-2px) rotate(-2deg)" },
          "35%":  { transform: "translateX(-22px) translateY(-8px) rotate(3deg)" },
          "65%":  { transform: "translateX(16px) translateY(-5px) rotate(-3deg)" },
          "100%": { transform: "translateX(0px) translateY(-2px) rotate(-2deg)" },
        },
        waterWave: {
          "0%, 100%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        bob: "bob 3s ease-in-out infinite",
        bobSlow: "bobSlow 4s ease-in-out infinite",
        bobDelay1: "bob 3.5s ease-in-out infinite 0.5s",
        bobDelay2: "bobSlow 4.2s ease-in-out infinite 1s",
        bobDelay3: "bob 3.8s ease-in-out infinite 1.5s",
        bobDelay4: "bobSlow 3.2s ease-in-out infinite 0.8s",
        revealBox: "revealBox 0.6s cubic-bezier(0.34,1.56,0.64,1) forwards",
        slideUp: "slideUp 0.4s ease-out forwards",
        fadeIn: "fadeIn 0.3s ease-out forwards",
        coinPop: "coinPop 0.8s ease-out forwards",
        giftShake: "giftShake 2.4s ease-in-out forwards",
        duckReveal: "duckReveal 0.7s cubic-bezier(0.34,1.56,0.64,1) forwards",
        swim1: "swim1 8s ease-in-out infinite",
        swim2: "swim2 9s ease-in-out infinite",
        swim3: "swim3 10s ease-in-out infinite",
        swim4: "swim4 7.5s ease-in-out infinite",
        swim5: "swim5 11s ease-in-out infinite",
        waterWave: "waterWave 3s linear infinite",
      },
    },
  },
  plugins: [],
};